nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5500']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        # expose_headers: ['Content-Type']
        allow_credentials: false
    paths:
        '^/': ~

